animeList/urls.py
from django.urls import path
from animeList import views

urlpatterns = [
    path('', views.home_view, name='home-page'),
    path('search_anime/', views.AnimeSearchView.as_view(), name='search-result'),
    path('details_anime/<int:pk>/', views.AnimeDetailView.as_view(), name='details-anime'),
    path('create_list/', views.CreateUserAnimeView.as_view(), name='create-list'),
    path('update_list/<int:pk>/', views.UpdateUserAnimeView.as_view(), name='update-list'),
    path('anime_list/', views.AnimeUserListView.as_view(), name='anime-list'),
    path('anime_update_list/<int:pk>/', views.AnimeUserUpdateView.as_view(), name='anime-update-list'),
    path('stats', views.stats_view, name='stats'),

]

pal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

from userManagement.forms import AuthenticationNewForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("userManagement.urls")),
    path("", include("animeList.urls")),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path("", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animeList/models.py
from django.db import models
from django.db.models import Avg

from userManagement.models import CustomUser


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Anime(models.Model):
    STATUS = [
        ('ONGOING', 'ongoing'),
        ('FINISHED', 'finished'),
        ('UPCOMING', 'upcoming'),
        ('UNKNOWN', 'unknown'),
    ]
    TYPE = [
        ('SPECIAL', 'special'),
        ('TV', 'tv'),
        ('MOVIE', 'movie'),
        ('OVA', 'ova'),
        ('ONA', 'ona'),
        ('UNKNOWN', 'unknown'),
    ]
    SEASON = [
        ('SPRING', 'spring'),
        ('SUMMER', 'summer'),
        ('WINTER', 'winter'),
        ('FALL', 'fall'),
    ]
    title = models.CharField(max_length=300)
    type = models.CharField(max_length=100, choices=TYPE)
    episodes = models.CharField(max_length=10)
    status = models.CharField(max_length=80, choices=STATUS)
    year = models.IntegerField(null=True, blank=True)
    season = models.CharField(max_length=80, choices=SEASON)
    picture = models.CharField(max_length=100)
    thumbnail = models.CharField(max_length=100)
    relatedAnime = models.CharField(max_length=8000)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    def get_user_anime(self):
        return UserAnime.objects.filter(anime=self)

    def average_rating(self):
        if UserAnime.objects.filter(anime=self).aggregate(Avg('score'))['score__avg']:
            return f"Average user score: {UserAnime.objects.filter(anime=self).aggregate(Avg('score'))['score__avg']}"
        else:
            return 'Not rated yet'


class UserAnime(models.Model):
    SCORE = [
        (1, '(1) Appalling'),
        (2, '(2) Horrible'),
        (3, '(3) Very Bad'),
        (4, '(4) Bad'),
        (5, '(5) Average'),
        (6, '(6) Fine'),
        (7, '(7) Good'),
        (8, '(8) Very Good'),
        (9, '(9) Great'),
        (10, '(10) Masterpiece')
    ]
    WATCH_STATUS = [
        ('watching', 'Watching'),
        ('completed', 'Completed'),
        ('on-hold', 'On-hold'),
        ('dropped', 'Dropped'),
        ('plan_to_watch', 'Plan to Watch'),
    ]
    watch_status = models.CharField(max_length=50, choices=WATCH_STATUS)
    eps_seen = models.IntegerField(default=0)
    score = models.IntegerField(choices=SCORE, null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE)

    def __str__(self):
        return self.score

animeList/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import TextInput, Select, NumberInput

from animeList.models import Anime
from animeList.models import UserAnime
from django.contrib import messages


class UserAnimeForm(forms.ModelForm):
    class Meta:
        model = UserAnime
        fields = ['watch_status', 'eps_seen', 'score', 'anime']

        widgets = {
            'anime': forms.HiddenInput(),
            'watch_status': Select(attrs={'class': 'form-select'}),
            'eps_seen': NumberInput(attrs={'class': 'form-control'}),
            'score': Select(attrs={'class': 'form-select'})
        }

    def clean(self):
        cleaned_data = super().clean()
        watch_status = cleaned_data.get('watch_status')
        eps_seen = cleaned_data.get('eps_seen')
        anime = cleaned_data.get('anime')
        max_episodes = anime.episodes
        if watch_status == 'completed' and int(eps_seen) < int(max_episodes):
            raise ValidationError(f'Cannot be set as "completed" since you have seen {eps_seen}/{max_episodes} eps')
        if int(eps_seen) > int(max_episodes):
            raise ValidationError(f'Maximum number of episodes is: {max_episodes}')
        return cleaned_data


class UserAnimeUpdateForm(forms.ModelForm):
    # am specificat in init asta ca sa pot sa trimit self.request din form
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserAnimeUpdateForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserAnime
        fields = ['score', 'eps_seen', 'watch_status']

    def clean(self):
        cleaned_data = super().clean()
        watch_status = cleaned_data.get('watch_status')
        eps_seen = cleaned_data.get('eps_seen')
        anime = self.instance.anime
        max_episodes = anime.episodes
        if watch_status == 'completed' and int(eps_seen) < int(max_episodes):
            raise ValidationError(f'Cannot be set as "completed" since you have seen {eps_seen}/{max_episodes} eps')
        return cleaned_data

animeList/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from animeList.models import Anime, UserAnime
from animeList.forms import UserAnimeForm, UserAnimeUpdateForm
from django.shortcuts import render
import random
from animeList.filters import AnimeFilter, AnimeListFilter


def home_view(request):
    # Niste titluri din baza de data aveau caractere nesuportate, le-am sters cu codul comentat de mai jos
    # to_delete = []
    # for a in Anime.objects.all():
    #     try:
    #         print(a.id, a.title)
    #     except:
    #         to_delete.append(a)
    # for a in to_delete:
    #     print(f'Deleting {a.id}')
    #     a.delete()
    all_animes = Anime.objects.filter(tags__name__in=['family friendly', 'family life']).exclude(picture='').exclude(
        picture='https://raw.githubusercontent.com/manami-project/anime-offline-database/master/pics/no_pic.png')
    obj_to_select = 4
    random_anime = random.sample(list(all_animes), obj_to_select)
    fact_list = [
        'Anime is a style of animation that originated in Japan and has become popular worldwide.',
        'The word "anime" is derived from the English word "animation."',
        'The first anime film ever made is "Momotaro, Sacred Sailors," released in 1945.',
        'Astro Boy, created by Osamu Tezuka in 1963, is considered one of the first successful anime series.',
        'Hayao Miyazaki is one of the most renowned anime directors, known for films like "Spirited Away" and "My Neighbor Totoro."',
        '"Dragon Ball Z" is one of the most popular and influential anime series worldwide.',
        '"Naruto" is another widely popular anime series, known for its compelling characters and epic battles.',
        '"One Piece" holds the Guinness World Record for the most copies published for the same comic book series by a single author.',
        '"Pokémon" is a globally recognized anime franchise, known for its video games, trading cards, and animated series.',
        '"Attack on Titan" is a dark fantasy anime series that has gained widespread acclaim for its intense action and compelling story.',
        'Studio Ghibli is a renowned Japanese animation studio responsible for many beloved anime films.',
        '"Death Note" is a psychological thriller anime series about a high school student who gains the power to kill anyone by writing their name in a notebook.',
        '"Fullmetal Alchemist" is a popular anime series known for its complex storyline and well-developed characters.',
        '"Sailor Moon" is a classic magical girl anime series that has inspired generations of fans.',
        '"Cowboy Bebop" is a critically acclaimed anime series that blends elements of science fiction, noir, and jazz music.',
        '"Neon Genesis Evangelion" is a groundbreaking mecha anime series known for its psychological themes and complex narrative.'
    ]
    random_fact = random.choice(fact_list)
    # The following block of code is for getting some soft stats as in: the user's
    # avg score, no of animes in list, favorite tags
    if request.user.is_authenticated:
        user = request.user
        number_rated_anime = UserAnime.objects.filter(user=user).count()
        scores = UserAnime.objects.filter(user=user).values('score')
        score_list = []
        for score in scores:
            if score['score'] is not None:
                score_list.append(score['score'])
        if UserAnime.objects.filter(user=user).exists() and len(score_list) > 0:
            avg_score = sum(score_list) / len(score_list)
            animes_in_user_list = UserAnime.objects.filter(user=user).values('anime')
            tags = []
            tags_count = {}
            for anime in animes_in_user_list:
                anime_tags = Anime.objects.filter(id=anime['anime']).values_list('tags__name', flat=True)
                tags.extend(anime_tags)
            for tag in tags:
                tags_count[tag] = tags_count.get(tag, 0) + 1
            tags_count = sorted(tags_count.items(), key=lambda x: x[1], reverse=True)[:5]

            context = {
                'random_anime': random_anime,
                'random_fact': random_fact,
                'soft_stats': [number_rated_anime, avg_score, tags_count]
            }
            return render(request, 'animeList/homepage.html', context)
        else:
            no_message, no_stats = 'No anime rated yet', 0
            context = {
                'random_anime': random_anime,
                'random_fact': random_fact,
                'no_soft_stats': [no_message, no_stats]
            }
            return render(request, 'animeList/homepage.html', context)
    else:
        no_message, no_stats = 'Log in to create you list', 0
        context = {
            'random_anime': random_anime,
            'random_fact': random_fact,
            'no_soft_stats': [no_message, no_stats]
        }
        return render(request, 'animeList/homepage.html', context)


class AnimeSearchView(LoginRequiredMixin, ListView):
    template_name = 'animeList/anime_search_list.html'
    model = Anime
    context_object_name = 'all_anime'

    def get_queryset(self):
        return Anime.objects.exclude(picture__isnull=True).exclude(picture='').exclude(
            picture='https://raw.githubusercontent.com/manami-project/anime-offline-database/master/pics/no_pic.png')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        # ce scriem in bara de search din navbar o sa fie si ca title in cea de advanced search
        q = self.request.GET.get('anime_title', '')
        adv_search_anime = Anime.objects.exclude(picture__isnull=True).exclude(picture='').exclude(
            picture='https://raw.githubusercontent.com/manami-project/anime-offline-database/master/pics/no_pic.png')
        myFilter = AnimeFilter(self.request.GET, queryset=adv_search_anime)
        adv_search_anime = myFilter.qs
        data['all_anime'] = adv_search_anime[:min(adv_search_anime.count(), 20)]
        data['filters'] = myFilter.form
        # randul de mai jos este ca sa ramana scris ce am cautat in bara de search, de asemenea in template a fost adaugat value="{{ q }}
        data['q'] = q
        return data


class AnimeDetailView(DetailView):
    model = Anime
    template_name = 'animeList/anime_detail_view.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        user_anime = UserAnime.objects.filter(anime=self.object, user=self.request.user).first()
        if user_anime is not None:
            form = UserAnimeForm(instance=user_anime)
        else:
            form = UserAnimeForm(initial={'anime': self.object})
        data['user_anime_form'] = form
        data['user_anime'] = user_anime
        return data


class CreateUserAnimeView(LoginRequiredMixin, CreateView):
    model = UserAnime
    form_class = UserAnimeForm
    template_name = 'animeList/user_anime_create.html'

    def get_success_url(self):
        return self.request.META['HTTP_REFERER']

    def form_valid(self, form):
        if form.is_valid():
            user_anime = form.save(commit=False)
            user_anime.user = self.request.user
            user_anime.save()
            messages.success(self.request, 'Anime added to list!')
            return redirect(self.get_success_url())
        return super().form_valid(form)


class UpdateUserAnimeView(LoginRequiredMixin, UpdateView):
    model = UserAnime
    form_class = UserAnimeForm
    template_name = 'animeList/user_anime_update.html'

    # success_url = reverse_lazy('home-page')

    def get_success_url(self):
        messages.success(self.request, 'Anime updated successfully!')
        return self.request.META['HTTP_REFERER']


class AnimeUserListView(LoginRequiredMixin, ListView):
    model = UserAnime
    template_name = 'animeList/anime_user_list_view.html'
    context_object_name = 'user_anime_list'

    def get_queryset(self):
        user = self.request.user
        return UserAnime.objects.filter(user=user.id)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        anime_in_list = UserAnime.objects.filter(user=self.request.user.id)
        myFilter = AnimeListFilter(self.request.GET, queryset=anime_in_list)
        anime_in_list = myFilter.qs
        data['user_anime_list'] = anime_in_list
        data['filters'] = myFilter.form
        return data


class AnimeUserUpdateView(LoginRequiredMixin, UpdateView):
    model = UserAnime
    template_name = 'animeList/user_anime_update_view.html'
    form_class = UserAnimeUpdateForm

    # so that you can get self.request from form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        messages.success(self.request, 'Anime updated successfully!')
        return self.request.META['HTTP_REFERER']

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        initial = super().get_initial()
        # : UserAnime s-a folosit ca sa specificam clasa, ca sa iti faca autofill (ex linia 149)
        user_anime: UserAnime = self.object
        form.fields['eps_seen'].widget.attrs.update(
            {'class': 'form-control', 'min': '0', 'max': f'{user_anime.anime.episodes}'})
        form.fields['score'].widget.attrs.update(
            {'class': 'form-control'})
        form.fields['watch_status'].widget.attrs.update(
            {'class': 'form-control'})
        return form


@login_required()
def stats_view(request):
    user = request.user
    scores = []
    for i in range(1, 11):
        scores_grade = UserAnime.objects.filter(user=user, score=i).count()

templates/animeList/anime_detail_view.html
{% extends 'base.html' %}
{% block title %} Anime Details {% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 offset-md-4 gy-5 col-12">
                <div class="card col-12">
                    <img src="{{ anime.picture }}" class="card-img-top" style="height: 360px; object-fit: fill"
                         alt="anime pic">
                    <div class="card-body">
                        <h5 title="{{ anime.title }}"
                            class="card-title custom_card_title">{{ anime.title }}</h5>
                        {% for message in messages %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <p class="card-text"> Tags: </p>
                        <ul class="tags-cell-detail-view">
                            {% for tag in anime.tags.all %}
                                <span class="tag"><a href="http://localhost:8000/seach_anime/?anime_title=&anime_status=&anime_type=&anime_year=&anime_season=&anime_tags={{ tag }}">{{ tag }}</a> </span>
                            {% endfor %}
                        <br><br>
                        <button class="show-all-btn btn btn-secondary">Show All Tags</button>
                        <br>
                        <button class="hide-btn btn btn-secondary" style="display: none;">Hide</button>
                        </ul>

                        <p>
                            {% if anime.tags.count > 4 %}
                                {{ anime.tags.count|add:-4 }}
                            {% else %}
                                No
                            {% endif %}
                            tags remaining
                        </p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ anime.status }} / {{ anime.episodes }} episodes</li>
                        <li class="list-group-item">{{ anime.year }} {{ anime.season }}</li>
                        <li class="list-group-item">{{ anime.average_rating }}</li>
                    </ul>
                    <div>
                        <form action="
                                {% if user_anime %}{% url 'update-list' user_anime.id %}{% else %}
                                {% url 'create-list' %}?anime_id={{ anime.id }}{% endif %}"
                              method="post">
                            {% csrf_token %}
                            {{ user_anime_form.as_p }}
                            <button class="btn btn-primary" type="submit">Save</button>
                        </form>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
{% endblock %}

templates/animeList/anime_search_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-1 col-12">
                <br><br>
                <h3 style="text-align: center">Search result</h3>
                <br><br>
                <div class="row">
                    {% for anime in all_anime %}
                        {% include 'partials/anime_card.html' %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-3 offset-1">
                <br><br>
                <h3 style="text-align: center"> Advanced Filters </h3>
                <br><br>
                <div class="card" style="width: 18rem;">
                  <div class="card-header">
                    Featured
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form method="get" class="col-12">
                            {{ filters }}
                            <br>
                            <button type="submit" class="btn btn-primary">Search</button>
                        </form>
                    </li>
                  </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/animeList/anime_user_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-12">
                <br><br>
                <h3 style="text-align: center">{{ user.first_name }}'s List</h3>
                <br><br>
                <div class="row">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Image</th>
                            <th scope="col">Anime title</th>
                            <th scope="col">Score</th>
                            <th scope="col">Type</th>
                            <th scope="col">Progress</th>
                            <th scope="col">Status</th>
                            <th scope="col">View tags</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody class="table-group-divider">
                        {% for user_anime in user_anime_list %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td><img src="{{ user_anime.anime.thumbnail }}" alt="anime pic" style="height: 70px; width: 60px"></td>
                                <td class="anime_list_row" title="{{ user_anime.anime.title }}">{{ user_anime.anime.title }}</td>
                                <td>{{ user_anime.get_score_display }}</td>
                                <td>{{ user_anime.anime.type }}</td>
                                <td>{{ user_anime.eps_seen }} / {{ user_anime.anime.episodes }}</td>
                                <td>{{ user_anime.get_watch_status_display }}</td>
                                <td class="tags-cell">
                                    {% for tag in user_anime.anime.tags.all %}
                                        <span class="tag"><a href="http://localhost:8000/seach_anime/?anime_title=&anime_status=&anime_type=&anime_year=&anime_season=&anime_tags={{ tag }}">{{ tag }}</a>,</span>
                                    {% endfor %}
                                    <button class="show-all-btn btn btn-secondary">Show All Tags</button>
                                    <br>
                                    <button class="hide-btn btn btn-secondary" style="display: none;">Hide</button>

                                </td>
                                <td> <a href="{% url 'anime-update-list' user_anime.id %}" class="btn btn-primary">Edit anime</a></td>
                            </tr>
                            <tr>
                                <td></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-3">
                <br><br>
                <h3 style="text-align: center"> My List Filters </h3>
                <br><br><br><br>
                <div class="card" style="width: 18rem;">
                  <div class="card-header">
                    Filters
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form method="get" class="col-12">
                            {{ filters }}
                            <br>
                            <button type="submit" class="btn btn-primary">Search</button>
                        </form>
                    </li>
                  </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/animeList/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-1 col-12">
                <br><br>
                <h3 style="text-align: center; color: black">Something you might like</h3>
                <br><br>
                <div class="row">
                    {% for anime in random_anime %}
                        {% include 'partials/anime_card.html' %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-3 offset-1 gy-5">
                <br><br><br><br><br>
                <div class="row">
                    <div class="card text-bg-primary mb-3" style="max-width: 18rem">
                      <div class="card-header">The More You Know</div>
                      <div class="card-body" style="line-height: 1.5; height: 9lh">
                        <h5 class="card-title">Anime facts</h5>
                            <p class="card-text" style="vertical-align: center; color: #e2e5ea">{{ random_fact }}</p>
                      </div>
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
                      <div class="card-header">This account</div>
                      <div class="card-body" style="line-height: 1.5">
                        <h5 class="card-title">Soft stats</h5>
                        <p class="card-text" style="color: #e2e5ea">Total anime in list: {{ soft_stats.0 }}{{ no_soft_stats.0 }}</p>
                        <p class="card-text" style="color: #e2e5ea">Average score of all anime rated: {{ soft_stats.1|floatformat:"2" }}{{ no_soft_stats.1 }}</p>
                        <p class="card-text" style="color: #e2e5ea">Top 5 tags: {{ no_soft_stats.1 }}</p>
                        {% for item in soft_stats.2 %}
                            <p class="card-text" style="color: #e2e5ea">{{ item.0|title }}: {{ item.1 }} </p>
                        {% endfor %}
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/animeList/stats.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Stats {% endblock %}
{% block content %}
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages': ['bar']});
        google.charts.setOnLoadCallback(drawScoresChart);

        function drawScoresChart() {
            var dataArray = [['Grade', 'Rated anime']];

            // Loop through the scores array and add each score and its corresponding count to the data array
            {% for score in scores %}
                dataArray.push(["{{ score.0 }}", {{ score.1 }}]);
            {% endfor %}

            var data = new google.visualization.arrayToDataTable(dataArray);

            var options = {
                title: 'Grades',
                width: 900,
                height: 500,
                legend: {position: 'none'},
                chart: {
                    title: 'Grades',
                    subtitle: "See what grades you've used"
                },
                bars: 'horizontal', // Required for Material Bar Charts.
                axes: {
                    x: {
                        0: {side: 'top', label: 'Rated Anime'} // Top x-axis.
                    }
                },
                bar: {groupWidth: "90%"}
            };

            var chart = new google.charts.Bar(document.getElementById('scores_chart'));
            chart.draw(data, options);
        };

        google.charts.setOnLoadCallback(drawTagsChart);

        function drawTagsChart() {
            var dataArray = [['Tags', 'No of anime']];

            // Loop through the tags array and add each tag and its corresponding count to the data array
            {% for tag in tags %}
                dataArray.push(["{{ tag.0 }}", {{ tag.1 }}]);
            {% endfor %}

            var data = new google.visualization.arrayToDataTable(dataArray);

            var options = {
                width: 900,
                height: 600,  
                legend: { position: 'none' },
                chart: {
                    title: 'Most seen tags',
                    subtitle: 'See your favorite tags' 
                },
                axes: {
                    x: {
                        0: { side: 'top', label: 'Tags'} // Top x-axis.
                    }
                },
                bar: { groupWidth: "90%" }
            };

            var chart = new google.charts.Bar(document.getElementById('tags_chart'));
            chart.draw(data, google.charts.Bar.convertOptions(options));
        };
        
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawPieChart);

        function drawPieChart() {

            
            var dataArray = [['Watch status', 'Anime']]

            {% for status in statuses %}
                dataArray.push(["{{ status.0 }}", {{ status.1 }}]);
            {% endfor %}
            
            var data = google.visualization.arrayToDataTable(dataArray);
        
            var options = {
                title: 'My Watch Statuses'
            };

            var chart = new google.visualization.PieChart(document.getElementById('piechart'));

            chart.draw(data, options);
        }
    </script>
    
    <br><br>
    <div class="col-md-11 col-12">
        <div class="row">
            <div style="padding-left: 50px" id="scores_chart"></div>
        </div>
    </div>
    <br><br><br>

    <div style="padding-left: 50px" id="tags_chart"></div>
    
    <div id="piechart" style="padding-left: 50px; width: 1000px; height: 600px;"></div>
{% endblock %}

templates/animeList/user_anime_create.html
{% extends 'base.html' %}
{% block title %}Add a new anime{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 offset-md-4 gy-5 col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
     </div>
{% endblock %}

templates/animeList/user_anime_update.html
{% extends 'base.html' %}
{% block title %}Update anime{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 offset-md-4 gy-5 col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
     </div>
{% endblock %}